package com.shang.jetpackmoviekmp.core.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val Primary = Color(0xFF3B82F6)
internal val OnPrimary = Color(0xFFFFFFFF)
internal val PrimaryContainer = Color(0xFFDBEAFE)
internal val OnPrimaryContainer = Color(0xFF1E3A8A)
internal val Secondary = Color(0xFF64748B)
internal val OnSecondary = Color(0xFFFFFFFF)
internal val SecondaryContainer = Color(0xFFD1D5DB)
internal val OnSecondaryContainer = Color(0xFF1E293B)
internal val Tertiary = Color(0xFF6366F1)
internal val OnTertiary = Color(0xFFFFFFFF)
internal val TertiaryContainer = Color(0xFFE0E7FF)
internal val OnTertiaryContainer = Color(0xFF3730A3)
internal val Error = Color(0xFFB3261E)
internal val OnError = Color(0xFFFFFFFF)
internal val ErrorContainer = Color(0xFFF9DEDC)
internal val OnErrorContainer = Color(0xFF410E0B)
internal val Background = Color(0xFFFFFFFF)
internal val OnBackground = Color(0xFF1E293B)
internal val Surface = Color(0xFFFFFFFF)
internal val OnSurface = Color(0xFF1E293B)
internal val SurfaceVariant = Color(0xFFF1F5F9)
internal val OnSurfaceVariant = Color(0xFF475569)
internal val InverseSurface = Color(0xFF1E293B)
internal val InverseOnSurface = Color(0xFFF1F5F9)
internal val Outline = Color(0xFFE2E8F0)
internal val OutlineVariant = Color(0xFFF1F5F9)
internal val DarkPrimary = Color(0xFF181A20)
internal val DarkOnPrimary = Color(0xFFF1F5F9)
internal val DarkPrimaryContainer = Color(0xFF23262F)
internal val DarkOnPrimaryContainer = Color(0xFFE0E7FF)
internal val DarkSecondary = Color(0xFF23262F)
internal val DarkOnSecondary = Color(0xFFD1D5DB)
internal val DarkSecondaryContainer = Color(0xFF343843)
internal val DarkOnSecondaryContainer = Color(0xFFE2E8F0)
internal val DarkTertiary = Color(0xFF373A47)
internal val DarkOnTertiary = Color(0xFFE0E7FF)
internal val DarkTertiaryContainer = Color(0xFF23262F)
internal val DarkOnTertiaryContainer = Color(0xFFB6C1FF)
internal val DarkError = Color(0xFFCF6679)
internal val DarkOnError = Color(0xFF1A1B1F)
internal val DarkErrorContainer = Color(0xFF8C1D18)
internal val DarkOnErrorContainer = Color(0xFFF9DEDC)
internal val DarkBackground = Color(0xFF101217)
internal val DarkOnBackground = Color(0xFFE5E7EB)
internal val DarkSurface = Color(0xFF181A20)
internal val DarkOnSurface = Color(0xFFE5E7EB)
internal val DarkSurfaceVariant = Color(0xFF23262F)
internal val DarkOnSurfaceVariant = Color(0xFFB6BFC8)
internal val DarkInverseSurface = Color(0xFFE5E7EB)
internal val DarkInverseOnSurface = Color(0xFF181A20)
internal val DarkOutline = Color(0xFF343843)
internal val DarkOutlineVariant = Color(0xFF23262F)

/** 電影評分星星使用的金色。 */
val StarRatingColor = Color(0xFFFFD700)
